version: '3.4'

services:
  catalogdb:
    image: postgres:16  # or just 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  catalog.api:
    build:
      context: ./Services/Catalog/Catalog.API  # The path to your Catalog.API project
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - catalogdb

volumes:
  postgres_catalog: