version: '3.4'

services:
  catalogdb:
    image: postgres:16  # or just 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    build:
      context: ./Services/Catalog/Catalog.API  # The path to your Catalog.API project
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - catalogdb

  basket.api:
    build:
      context: ./Services/Basket/Basket.API 
      dockerfile: Dockerfile
    ports:
      - "8081:81"
    depends_on:
      - basketdb

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  discount_data:

